#!/usr/bin/env python3
import argparse
import base64
import hashlib
import os
import stat
import textwrap
import zlib
from pathlib import Path


def py_string_literal(name, data):
    encoded = base64.b64encode(zlib.compress(data, 9)).decode('ascii')
    chunks = textwrap.wrap(encoded, 76)
    body = '\n'.join(f'    "{chunk}"' for chunk in chunks)
    return f'{name} = (\n{body}\n)\n'


def main():
    parser = argparse.ArgumentParser(description='Embed MEGAHIT Python launcher and core binary into one executable.')
    parser.add_argument('--launcher', required=True)
    parser.add_argument('--core', required=True)
    parser.add_argument('--output', required=True)
    args = parser.parse_args()

    launcher = Path(args.launcher).read_bytes()
    core = Path(args.core).read_bytes()
    digest = hashlib.sha256(core + b'\0' + launcher).hexdigest()

    script = f'''#!/usr/bin/env python3
# Generated by cmake/embed_megahit.py. Do not edit this file directly.
import base64
import hashlib
import os
import shutil
import stat
import sys
import tempfile
import zlib

EMBEDDED_HASH = "{digest}"
'''
    script += py_string_literal('CORE_B64', core)
    script += py_string_literal('LAUNCHER_B64', launcher)
    script += r'''


def _decode(blob):
    return zlib.decompress(base64.b64decode(blob.encode('ascii')))


def _safe_symlink(src, dst):
    try:
        if os.path.lexists(dst):
            current = os.readlink(dst) if os.path.islink(dst) else None
            if current == src:
                return
            os.unlink(dst)
        os.symlink(src, dst)
    except OSError:
        if not os.path.exists(dst):
            shutil.copy2(src, dst)
            os.chmod(dst, os.stat(dst).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _link_test_data(runtime_root, real_exe_dir):
    candidates = [
        os.path.abspath(os.path.join(real_exe_dir, '..', 'test_data')),
        os.path.abspath(os.path.join(real_exe_dir, '..', 'share', 'megahit', 'test_data')),
    ]
    existing = next((path for path in candidates if os.path.isdir(path)), None)
    if existing is None:
        return

    direct_link = os.path.join(runtime_root, 'test_data')
    share_dir = os.path.join(runtime_root, 'share', 'megahit')
    os.makedirs(share_dir, exist_ok=True)
    share_link = os.path.join(share_dir, 'test_data')
    _safe_symlink(existing, direct_link)
    _safe_symlink(existing, share_link)


def _prepare_runtime():
    real_exe = os.path.realpath(sys.argv[0])
    real_exe_dir = os.path.dirname(real_exe)
    cache_base = os.environ.get('MEGAHIT_EMBED_CACHE') or os.path.join(tempfile.gettempdir(), 'megahit-embedded')
    runtime_root = os.path.join(cache_base, EMBEDDED_HASH)
    runtime_bin = os.path.join(runtime_root, 'bin')
    os.makedirs(runtime_bin, exist_ok=True)

    core_path = os.path.join(runtime_bin, 'megahit_core')
    marker_path = os.path.join(runtime_root, '.hash')
    if not os.path.exists(core_path) or not os.path.exists(marker_path) or open(marker_path).read().strip() != EMBEDDED_HASH:
        tmp_path = core_path + '.tmp'
        with open(tmp_path, 'wb') as out:
            out.write(_decode(CORE_B64))
        os.chmod(tmp_path, os.stat(tmp_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        os.replace(tmp_path, core_path)
        with open(marker_path, 'w') as out:
            out.write(EMBEDDED_HASH + '\n')

    _safe_symlink('megahit_core', os.path.join(runtime_bin, 'megahit_core_popcnt'))
    _safe_symlink('megahit_core', os.path.join(runtime_bin, 'megahit_core_no_hw_accel'))
    _link_test_data(runtime_root, real_exe_dir)
    return runtime_bin


def _run_launcher():
    runtime_bin = _prepare_runtime()
    launcher_source = _decode(LAUNCHER_B64).decode('utf-8')
    globals_dict = {
        '__name__': '__main__',
        '__file__': os.path.join(runtime_bin, 'megahit'),
        '__package__': None,
        '__cached__': None,
    }
    sys.argv[0] = os.path.realpath(sys.argv[0])
    code = compile(launcher_source, globals_dict['__file__'], 'exec')
    exec(code, globals_dict)


if __name__ == '__main__':
    _run_launcher()
'''

    output = Path(args.output)
    output.write_text(script)
    mode = output.stat().st_mode
    output.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


if __name__ == '__main__':
    main()
